# Generated by Django 4.1.2 on 2023-07-14 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('joining_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('qualification', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='employee', max_length=50)),
                ('permission', models.JSONField(default='{access:all}')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='created_team_collection', to='my_app.employee')),
                ('employee', models.ManyToManyField(related_name='team_collections', to='my_app.employee')),
                ('role', models.ManyToManyField(to='my_app.role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='my_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('progress', 'progress'), ('complete', 'complete')], max_length=20)),
                ('client_name', models.CharField(max_length=50)),
                ('communicator', models.CharField(max_length=50)),
                ('main_developer', models.CharField(max_length=70)),
                ('helper_developer', models.CharField(max_length=70)),
                ('estimated_hours', models.CharField(max_length=70)),
                ('platform', models.CharField(max_length=70)),
                ('started_date', models.DateField()),
                ('completed_date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='my_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('started_date', models.DateField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.task')),
            ],
        ),
    ]
